server="mongodb://testninja:password123@ds149491.mlab.com:49491/dinesty_ninja_db"
database="dinesty_ninja_db"

yelpURL="https://api.yelp.com/v3/businesses/"
yelpKey="WWZ_RGmgqAfKbGMg80ffJ4bgzzDsO3PZGfXASTkkEeBb6Xi4Ue9C6gF1vp5MRxXze0IlgRIDPotXy6kQRaIMUkZ-r9ST2HsloZQTDVYjX2sOCpk9ymvYkU-fNP4zXHYx"