server="mongodb://dineninja:#d0G!efp3NY8aX$dwj2e@ds149491.mlab.com:49491/dinesty_ninja_db"
database="dinesty_ninja_db"

yelpURL="https://api.yelp.com/v3/businesses/"
yelpKey="vapirtuamS3uFrGYaSP9OdH3oF1v-S6rH35KLXLB2il6WRFKLKB6ycBYF_6DQ-xUZ17jLNjdlXDGXpqKry9Vo7GSveIoCf3_jPtcBCUijcU8_DXkY9wZvAQLVb8yXHYx"