server="mongodb://testninja:password123@ds149491.mlab.com:49491/dinesty_ninja_db"
database="dinesty_ninja_db"

yelpURL="https://api.yelp.com/v3/businesses/"
yelpKey="K6_e-7ke5A3a4iTcVl5NUEQHyAGaAvllCjHByHbBjLXWjR9VkANihPMl7HoJJZh8bdDKSE_qAe4jbJ5uMQyVR3eYy45NAIYwZ0hpW5qyjlumuO11MLP_ewn1c6EzXHYx"