server="mongodb://ninja:ninja123@ds149491.mlab.com:49491/dinesty_ninja_db"
database="dinesty_ninja_db"

yelpURL="https://api.yelp.com/v3/businesses/"
yelpKey="HHvd5iD1YxEkTaHlFi1_lSrFJE76Yb-xKmNDJnkPMFaRJoTehBuX3BVgDiQKfslO-mSBwZ4BvGrYE6akvWSOCaHcWvVjCmX4fpnd1TUmy4h2Cx3mg4ghsI6KN-8uXHYx"

